services:
  mongodb:
    image: mongo:8
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: attachments
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - '27018:27017'
    command: '--bind_ip_all --quiet --logpath /dev/null --replSet rs0'

  mongo-init:
    image: mongo:8
    restart: 'no'
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval
      '
      rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 0, host: "localhost:27017" }
         ]
      })
      '

volumes:
  mongo:
